#!/bin/bash 
   
source $PWD/install_docker
source $PWD/remove_docker 

echo "1) Install Docker"
echo "2) Remove Docker" 

read choice 

case $choice in 
   1) install_docker ;; 

   2) remove_docker ;;

   *) echo "wrong choice" ;;
esac   
    



 
 
    
